// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKcrjClAY7tCHp5rdhUjHPJXMIhdSFBII',
    appId: '1:551439676652:web:923ab304dc3307365b61c9',
    messagingSenderId: '551439676652',
    projectId: 'bilgiseruveni-6c971',
    authDomain: 'bilgiseruveni-6c971.firebaseapp.com',
    storageBucket: 'bilgiseruveni-6c971.appspot.com',
    measurementId: 'G-YSPT4SVFRN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwDX1Wf8LWZSrAfd42lshevScgyLe_f2g',
    appId: '1:551439676652:android:bc56ab7ec1a0561d5b61c9',
    messagingSenderId: '551439676652',
    projectId: 'bilgiseruveni-6c971',
    storageBucket: 'bilgiseruveni-6c971.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCajUBWBWAMEcMXvE-9QUHYGcopAEq5lBM',
    appId: '1:551439676652:ios:ef31539f13c450835b61c9',
    messagingSenderId: '551439676652',
    projectId: 'bilgiseruveni-6c971',
    storageBucket: 'bilgiseruveni-6c971.appspot.com',
    androidClientId: '551439676652-7ntlo0235bv5v3ole8ok86i7e0g5699d.apps.googleusercontent.com',
    iosClientId: '551439676652-o6hjje4m1vvjg74nnogjbdae4r46eue3.apps.googleusercontent.com',
    iosBundleId: 'com.example.mindflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCajUBWBWAMEcMXvE-9QUHYGcopAEq5lBM',
    appId: '1:551439676652:ios:ef31539f13c450835b61c9',
    messagingSenderId: '551439676652',
    projectId: 'bilgiseruveni-6c971',
    storageBucket: 'bilgiseruveni-6c971.appspot.com',
    androidClientId: '551439676652-7ntlo0235bv5v3ole8ok86i7e0g5699d.apps.googleusercontent.com',
    iosClientId: '551439676652-o6hjje4m1vvjg74nnogjbdae4r46eue3.apps.googleusercontent.com',
    iosBundleId: 'com.example.mindflow',
  );
}
